"""Entry point for the weekly performance report.

Runs weekly. Calculates risk-adjusted performance metrics, compares to SPY
benchmark, and creates a GitHub issue with the performance report.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys

import structlog

from financial_agent.broker import AlpacaBroker
from financial_agent.config import AppConfig
from financial_agent.performance import PerformanceTracker
from financial_agent.persistence import EquityTracker
from financial_agent.utils.logging import setup_logging


def _run_gh_command(cmd: list[str]) -> tuple[bool, str]:
    """Run a gh CLI command. Returns (success, output_or_error)."""
    log = structlog.get_logger()
    try:
        result = subprocess.run(  # noqa: S603, S607
            cmd,
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode == 0:
            return True, result.stdout.strip()
        else:
            log.error("gh_command_failed", cmd=cmd[:3], stderr=result.stderr.strip())
            return False, result.stderr.strip()
    except (subprocess.TimeoutExpired, FileNotFoundError) as e:
        log.error("gh_command_error", cmd=cmd[:3], error=str(e))
        return False, str(e)


def main() -> None:
    """Generate and publish the weekly performance report."""
    config = AppConfig()
    setup_logging(config.log_level)
    log = structlog.get_logger()

    log.info("performance_report_started")

    broker = AlpacaBroker(config.broker)
    equity_tracker = EquityTracker(config.data.data_dir)
    perf_tracker = PerformanceTracker(config.data.data_dir)

    # Get current portfolio for context
    portfolio = broker.get_portfolio_snapshot()

    # Calculate metrics
    daily_returns = equity_tracker.daily_returns(90)
    sharpe = perf_tracker.sharpe_ratio(daily_returns)
    sortino = perf_tracker.sortino_ratio(daily_returns)
    win_rate = perf_tracker.win_rate()
    profit_factor = perf_tracker.profit_factor()
    avg_win = perf_tracker.avg_win()
    avg_loss = perf_tracker.avg_loss()
    max_dd = equity_tracker.max_drawdown(90)
    current_dd = equity_tracker.current_drawdown(portfolio.equity)
    trade_count = perf_tracker.trade_count()

    # Build report
    metrics_rows = [
        f"| Sharpe Ratio (90d) | {sharpe:.2f} |" if sharpe is not None else "",
        f"| Sortino Ratio (90d) | {sortino:.2f} |" if sortino is not None else "",
        f"| Win Rate | {win_rate:.1%} |" if win_rate is not None else "",
        f"| Profit Factor | {profit_factor:.2f} |" if profit_factor is not None else "",
        f"| Avg Win | ${avg_win:,.2f} |" if avg_win is not None else "",
        f"| Avg Loss | ${avg_loss:,.2f} |" if avg_loss is not None else "",
        f"| Max Drawdown (90d) | {max_dd:.1%} |",
        f"| Current Drawdown | {current_dd:.1%} |",
        f"| Total Trades | {trade_count} |",
        f"| Peak Equity | ${equity_tracker.peak():,.2f} |",
        f"| Current Equity | ${portfolio.equity:,.2f} |",
    ]
    metrics_table = "\n".join(r for r in metrics_rows if r)

    # Assessment
    assessment_parts = []
    if sharpe is not None:
        if sharpe >= 2.0:
            assessment_parts.append("Excellent risk-adjusted returns (Sharpe >= 2)")
        elif sharpe >= 1.0:
            assessment_parts.append("Good risk-adjusted returns (Sharpe >= 1)")
        elif sharpe >= 0:
            assessment_parts.append("Positive but low risk-adjusted returns")
        else:
            assessment_parts.append("Negative risk-adjusted returns — needs review")

    if win_rate is not None:
        if win_rate >= 0.6:
            assessment_parts.append(f"Strong win rate ({win_rate:.0%})")
        elif win_rate >= 0.4:
            assessment_parts.append(f"Acceptable win rate ({win_rate:.0%})")
        else:
            assessment_parts.append(f"Low win rate ({win_rate:.0%}) — check entry criteria")

    if max_dd > 0.15:
        assessment_parts.append(f"High max drawdown ({max_dd:.1%}) — risk controls need tightening")

    if assessment_parts:
        assessment = "\n".join(f"- {p}" for p in assessment_parts)
    else:
        assessment = "Insufficient data for assessment."

    issue_body = f"""## Weekly Performance Report

### Portfolio Status
- **Equity:** ${portfolio.equity:,.2f}
- **Cash:** ${portfolio.cash:,.2f}
- **Positions:** {portfolio.position_count}

### Performance Metrics

| Metric | Value |
|--------|-------|
{metrics_table}

### Assessment
{assessment}

### Data Coverage
- Equity history: {len(equity_tracker.daily_returns(365))} daily records
- Trade journal: {trade_count} trades recorded

---
_This report was automatically generated by the performance reporting agent._
"""

    # Create the issue
    cmd = [
        "gh",
        "issue",
        "create",
        "--title",
        f"Performance Report — Sharpe: {sharpe:.2f}" if sharpe else "Performance Report",
        "--body",
        issue_body,
        "--label",
        "performance-report",
        "--label",
        "automated",
    ]
    _run_gh_command(cmd)

    _write_github_output(
        {
            "equity": portfolio.equity,
            "sharpe": sharpe,
            "win_rate": win_rate,
            "max_drawdown": max_dd,
            "trade_count": trade_count,
        }
    )

    log.info("performance_report_complete", sharpe=sharpe, win_rate=win_rate)


def _write_github_output(data: dict[str, object]) -> None:
    """Write summary to GITHUB_OUTPUT."""
    output_file = os.environ.get("GITHUB_OUTPUT")
    if output_file:
        with open(output_file, "a") as f:
            f.write(f"summary={json.dumps(data)}\n")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        log = structlog.get_logger()
        log.error("performance_report_fatal_error", error=str(e), exc_info=True)
        sys.exit(1)
